table Date
	lineageTag: 4ab15321-1328-47b2-919b-8d3d0102195a

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: ce6fc61f-8ce9-4e5b-8b5c-187a74b2f8e5
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 89559694-fa1c-4249-a576-b74aa80e7478
			defaultHierarchy: LocalDateTable_7e30d256-b63a-4b21-ac46-9f542615784c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 9d9a68c5-ee62-4223-8642-72604a94484c
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		lineageTag: 16437b19-9969-41f8-bc58-b04cdf110bc1
		summarizeBy: sum
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 3c1be41f-7ec2-47c6-8a76-4ce678531800
		summarizeBy: none
		sourceColumn: MonthName

		annotation SummarizationSetBy = Automatic

	column YearMonth
		dataType: string
		lineageTag: 52aed2c2-6825-491f-a915-baa261684043
		summarizeBy: none
		sourceColumn: YearMonth
		sortByColumn: YearMonthSort

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 9f863ca6-47dc-4320-ab94-7e6fc6ff423e
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: string
		lineageTag: ac2ee1f4-2069-47cc-9849-2affa9efab6d
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column YearMonthSort = 'Date'[Year] * 100 + 'Date'[Month]
		formatString: 0
		lineageTag: cbb9c633-7e91-4956-b19f-2c8f98189196
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition Date = m
		mode: import
		source =
				let
				    StartDate = #date(2021, 1, 1),
				    EndDate = #date(2026, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    ToTable = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    ChangedType = Table.TransformColumnTypes(ToTable, {{"Date", type date}}),
				    AddYear = Table.AddColumn(ChangedType, "Year", each Date.Year([Date]), Int64.Type),
				    AddMonth = Table.AddColumn(AddYear, "Month", each Date.Month([Date]), Int64.Type),
				    AddMonthName = Table.AddColumn(AddMonth, "MonthName", each Date.ToText([Date], "MMM"), type text),
				    AddYearMonth = Table.AddColumn(AddMonthName, "YearMonth", each Date.ToText([Date], "yyyy-MM"), type text),
				    AddQuarter = Table.AddColumn(AddYearMonth, "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date])), type text),
				    AddDayOfWeek = Table.AddColumn(AddQuarter, "DayOfWeek", each Date.ToText([Date], "ddd"), type text)
				in
				    AddDayOfWeek

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

